[project]
name = "src"
version = "0.0.1"
description = "Fake News Detection Webapp"
authors = [{name = "Shiwang Upadhyay", email = "ushiwang1244a@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}
